var str='﻿<div class="c-footer">';
str+='		<div class="c-layout-footer-10-content container">';
str+='			<div class="row">';
str+='				<div class="col-md-5">';
str+='						<div class="row">';
str+='							<div class="c-layout-footer-10-title-container">';
str+='								<h3 class="c-layout-footer-10-title">BETSM高级版软件下载</h3>';
str+='								<div class="c-layout-footer-10-title-line"><span class="c-theme-bg"></span></div>';
str+='							</div>';
str+='							<p class="c-layout-footer-10-desc">';
str+='							';
str+='							<div class="c-content-events-1">';
str+='								<div class="c-content-events-1-item wow fadeInLeft" data-wow-delay="0.2s" style="opacity: 1; visibility: visible; animation-delay: 0.2s; animation-name: fadeInLeft;">';
str+='									<div class="c-content-events-1-content-container">';
str+='										<div class="c-left">';
str+='					                        <div class="c-icons">';
str+='					                            <a href="javascript:getSoftWare();"  style="width: auto;height: auto;padding: 13px;float: left;margin-left: -1px;"  target="_blank" class="c-font-30 c-font-blue-3 socicon-btn c-bg-grey-1-hover socicon-windows tooltips" data-original-title="Windows系统" data-container="body"></a>';
str+='					                            <a href="javascript:getSoftAndroid();" style="width: auto;height: auto;padding: 13px;float: left;margin-left: -1px;"  target="_blank" class="c-font-30 c-font-green-1 socicon-btn c-bg-grey-1-hover socicon-android tooltips" data-original-title="安卓系统" data-container="body"></a>';
str+='					                            <a href="javascript:getSoftIOS();" style="width: auto;height: auto;padding: 13px;float: left;margin-left: -1px;"  target="_blank" class="c-font-30 c-font-grey-3 socicon-btn c-bg-grey-1-hover socicon-apple tooltips" data-original-title="苹果系统" data-container="body"></a>';
str+='					                        </div>';
str+='					                    </div>';
str+='									</div>';
str+='								</div>';
str+='							</div>';
str+='						</div>';
str+='						<div style="margin-top:30px;" class="row">';
str+='							<div class="c-layout-footer-10-title-container">';
str+='								<h3 class="c-layout-footer-10-title">BETSM走地版软件下载</h3>';
str+='								<div class="c-layout-footer-10-title-line"><span class="c-theme-bg"></span></div>';
str+='							</div>';
str+='							<p class="c-layout-footer-10-desc">';
str+='							';
str+='							<div class="c-content-events-1">';
str+='								<div class="c-content-events-1-item wow fadeInLeft" data-wow-delay="0.3s" style="opacity: 1; visibility: visible; animation-delay: 0.2s; animation-name: fadeInLeft;">';
str+='									<div class="c-content-events-1-content-container">';
str+='										<div class="c-left">';
str+='					                        <div class="c-icons">';
str+='					                            <a href="javascript:getSoftWareRoll();"  style="width: auto;height: auto;padding: 13px;float: left;margin-left: -1px;"  target="_blank" class="c-font-30 c-font-blue-3 socicon-btn c-bg-grey-1-hover socicon-windows tooltips" data-original-title="Windows系统" data-container="body"></a>';
str+='					                            <a href="javascript:getSoftAndroidRoll();" style="width: auto;height: auto;padding: 13px;float: left;margin-left: -1px;"  target="_blank" class="c-font-30 c-font-green-1 socicon-btn c-bg-grey-1-hover socicon-android tooltips" data-original-title="安卓系统" data-container="body"></a>';
str+='					                            <a href="javascript:getSoftIOSRoll();" style="width: auto;height: auto;padding: 13px;float: left;margin-left: -1px;"  target="_blank" class="c-font-30 c-font-grey-3 socicon-btn c-bg-grey-1-hover socicon-apple tooltips" data-original-title="苹果系统" data-container="body"></a>';
str+='					                        </div>';
str+='					                    </div>';
str+='									</div>';
str+='								</div>';
str+='							</div>';
str+='						</div>';
str+='						<div class="row">';
str+=' 							<br>';
str+=' 							IOS用户使用safari浏览器安装。<br>';
str+=' 							禁止将帐号密码分享给他人，信息泄露、同一帐号异地同时登录，直接封停处理。<br><br>';
str+=' 						</div>';
str+='				</div>';
str+='				<div class="col-md-7">';
str+='					<div class="row">';
str+='						<div class="col-md-6">';
str+='							<div class="c-layout-footer-10-title-container">';
str+='								<h3 class="c-layout-footer-10-title">关于BetSPSSModeler</h3>';
str+='								<div class="c-layout-footer-10-title-line"><span class="c-theme-bg"> </span></div>';
str+='							</div>';
str+='							<ul class="c-layout-footer-10-list">';
str+='								<li class="c-layout-footer-10-list-item">为用户提供真实的货币价值</li>';
str+='								<li class="c-layout-footer-10-list-item">提供准确预测和利润的足球大数据软件平台</li>';
str+='								<li class="c-layout-footer-10-list-item">被超过两万的足球爱好者用作足球投注预测指南</li>';
str+='								<li class="c-layout-footer-10-list-item">本站提供软件仅限于足彩等数据分析研究</li>';
str+='								<li class="c-layout-footer-10-list-item">严禁使用本站提供数据用于任何违反当地法律活动</li>';
str+='							</ul>';
str+='						</div>';
str+='						<div class="col-md-3">';
str+='							<div class="c-layout-footer-10-title-container">';
str+='								<h3 class="c-layout-footer-10-title">关于产品</h3>';
str+='								<div class="c-layout-footer-10-title-line"><span class="c-theme-bg"> </span></div>';
str+='							</div>';
str+='							<ul class="c-layout-footer-10-list">';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/event/datas.html" rel="nofollow">应用技术</a></li>';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/event/softs.html" rel="nofollow">软件版本</a></li>';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/event/ycs.html" rel="nofollow">每日推荐</a></li>';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/event/teachs.html" rel="nofollow">足球教程</a></li>';
str+='							</ul>';
str+='						</div>';
str+='						<div class="col-md-3">';
str+='							<div class="c-layout-footer-10-title-container">';
str+='								<h3 class="c-layout-footer-10-title">相关链接</h3>';
str+='								<div class="c-layout-footer-10-title-line"><span class="c-theme-bg"> </span></div>';
str+='							</div>';
str+='							<ul class="c-layout-footer-10-list">';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/contact.html" rel="nofollow">足球分析软件</a></li>';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/roll.html" rel="nofollow">走地大球分析软件</a></li>';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/event/events.html" rel="nofollow">软件预测记录</a></li>';
str+='								<li class="c-layout-footer-10-list-item"><a href="http://www.betsoft366.com/product/help.html" rel="nofollow">软件使用帮助</a></li>';
str+='							</ul>';
str+='						</div>';
str+='					</div>';
str+='				</div>';
str+='			</div>';
str+='		</div>';
str+='		<div class="c-layout-footer-10-subfooter-container c-bg-grey">';
str+='			<div class="c-layout-footer-10-subfooter container">';
str+='				<div style="text-align:center;" class="c-layout-footer-10-subfooter-content">';
str+='					<img alt="图标" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/logo-black.png"  style="width:30px;" />';
str+='					 © 2017 BetSPSSModeler';
str+='				</div>';
str+='			</div>';
str+='		</div>';
str+='	</div>';
$("#footer").append(str.trim());