var initIndex = function () {

	var initBT = function () {
		var str='<div class="tp-banner-container tp-fullscreen tp-fullscreen-mobile c-arrow-darken" data-bullets-pos="center">';
		str+='        <div class="tp-banner rev_slider" data-version="5.0">';
		str+='            <ul>';
		str+='                <li data-index="rs-16" data-transition="zoomout" data-slotamount="default"  data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed="2000"  data-thumb="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/4.jpg"  data-rotate="0"  data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off"  >';
		str+='                    <img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/4.jpg"  alt="首页图片" data-bgposition="center center" data-kenburns="on" data-duration="15000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 0" data-offsetend="-500 500" data-bgparallax="10" class="rev-slidebg" data-no-retina>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-0 c-font-white c-font-bold" ';
		str+='                         id="slide-16-layer-1" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                                    data-fontsize="[\'70\',\'70\',\'70\',\'45\']"';
		str+='                        data-lineheight="[\'70\',\'70\',\'70\',\'50\']"';
		str+='                        data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                         data-transform_in="x:[105%];z:0;rX:45deg;rY:0deg;rZ:90deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" ';
		str+='                        data-start="1000" ';
		str+='                        data-splitin="chars" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        data-elementdelay="0.05" ';
		str+='                        style="z-index: 5; white-space: nowrap;">BetSM足球大数据 ';
		str+='                    </div>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-0 c-font-white" ';
		str+='                         id="slide-16-layer-4" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'52\',\'52\',\'52\',\'51\']" ';
		str+='                                    data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                         data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" ';
		str+='                        data-start="1500" ';
		str+='                        data-splitin="none" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        style="z-index: 6; white-space: nowrap;">专业足球分析软件';
		str+='                    </div>';
		str+='                    <div class="tp-caption NotGeneric-Icon   tp-resizeme rs-parallaxlevel-0" ';
		str+='                         id="slide-16-layer-8" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'-68\',\'-68\',\'-68\',\'-68\']" ';
		str+='                                    data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                            data-style_hover="cursor:default;"';
		str+='                         data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" ';
		str+='                        data-start="2000" ';
		str+='                        data-splitin="none" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        style="z-index: 7; white-space: nowrap;"><i class="pe-7s-refresh"></i> ';
		str+='                    </div>';
		str+='                </li>';
		str+='                <li data-index="rs-17" data-transition="fadetotopfadefrombottom" data-slotamount="default"  data-easein="Power3.easeInOut" data-easeout="Power3.easeInOut" data-masterspeed="1500"  data-thumb="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/7.jpg"  data-rotate="0"  data-saveperformance="off"  data-title="No Hassle" >';
		str+='                    <img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/7.jpg"  alt="首页图片"  data-bgposition="center center" data-kenburns="on" data-duration="15000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 500" data-offsetend="0 -500" data-bgparallax="10" class="rev-slidebg" data-no-retina>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-3 c-font-white c-font-bold" ';
		str+='                         id="slide-17-layer-1" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                                    data-fontsize="[\'70\',\'70\',\'70\',\'45\']"';
		str+='                        data-lineheight="[\'70\',\'70\',\'70\',\'50\']"';
		str+='                        data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                         data-transform_in="y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:0px;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;" ';
		str+='                        data-start="1000" ';
		str+='                        data-splitin="chars" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        data-elementdelay="0.05" ';
		str+='                        style="z-index: 5; white-space: nowrap;">借助预测算法和机器学习';
		str+='                    </div>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-2 c-font-white" ';
		str+='                         id="slide-17-layer-4" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'52\',\'52\',\'52\',\'51\']" ';
		str+='                                    data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                         data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:[100%];" ';
		str+='                         data-mask_out="x:inherit;y:inherit;" ';
		str+='                        data-start="1500" ';
		str+='                        data-splitin="none" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        style="z-index: 6; white-space: nowrap;">从容预测未来结果';
		str+='                    </div>';
		str+='                </li>';
		str+='                <li data-index="rs-20" data-transition="zoomin" data-slotamount="7"  data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed="2000"  data-thumb="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/8.jpg"  data-rotate="0"  data-saveperformance="off"  data-title="Love it?" >';
		str+='                    <img src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/8.jpg"  alt="首页图片"  data-bgposition="center center" data-kenburns="on" data-duration="15000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120" data-rotatestart="0" data-rotateend="0" data-offsetstart="0 -500" data-offsetend="0 500" data-bgparallax="10" class="rev-slidebg" data-no-retina>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-0 c-font-white c-font-bold" ';
		str+='                         id="slide-20-layer-1" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                                    data-fontsize="[\'70\',\'70\',\'70\',\'45\']"';
		str+='                        data-lineheight="[\'70\',\'70\',\'70\',\'50\']"';
		str+='                        data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                         data-transform_in="x:[-105%];z:0;rX:0deg;rY:0deg;rZ:-90deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" ';
		str+='                        data-start="1000" ';
		str+='                        data-splitin="chars" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        data-elementdelay="0.1" ';
		str+='                        style="z-index: 5; white-space: nowrap;">运用先进的分析云功能';
		str+='                    </div>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-0 c-font-white" ';
		str+='                         id="slide-20-layer-4" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'52\',\'52\',\'52\',\'51\']" ';
		str+='                                    data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                         data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" ';
		str+='                        data-start="1500" ';
		str+='                        data-splitin="none" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        style="z-index: 6; white-space: nowrap;">确保比赛朝正确的方向发展 ';
		str+='                    </div>';
		str+='                    <div class="tp-caption tp-resizeme rs-parallaxlevel-0" ';
		str+='                         id="slide-20-layer-8" ';
		str+='                         data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" ';
		str+='                         data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'105\',\'105\',\'105\',\'105\']" ';
		str+='                                    data-width="none"';
		str+='                        data-height="none"';
		str+='                        data-whitespace="nowrap"';
		str+='                        data-transform_idle="o:1;"';
		str+='                            data-style_hover="cursor:default;"';
		str+='                         data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1500;e:Power4.easeInOut;" ';
		str+='                         data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" ';
		str+='                         data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" ';
		str+='                         data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" ';
		str+='                        data-start="2000" ';
		str+='                        data-splitin="none" ';
		str+='                        data-splitout="none" ';
		str+='                        data-responsive_offset="on" ';
		str+='                        style="z-index: 7; white-space: nowrap;">';
		str+='                    </div>';
		str+='                </li>';
		str+='            </ul>';
		str+='        </div>';
		str+='    </div>';
		$("#main").append(str);
		str='';
		str+='<div class="container">';
		str+='		<div class="c-content-services-6">';
		str+='			<div class="c-content-title-1 c-opt-1 wow fadeInUp">';
		str+='				<h1 class="c-center c-font-bold">软件优势</h1>';
		str+='				<p class="c-font-center">将足球赛事预测探索运用到机器学习当中</p>';
		str+='				<div class="c-line-center c-theme-bg"></div>';
		str+='			</div>';
		str+='			<div class="row">';
		str+='				<div class="col-md-4 col-sm-6">';
		str+='					<div class="c-content-services-6-item wow fadeInUp" data-wow-delay="0s">';
		str+='						<div class="c-content-services-6-item-icon c-content-business-line-icon c-theme c-business-icon-13"></div>';
		str+='						<h4 class="c-content-services-6-item-title">机器学习</h4>';
		str+='						<p class="c-content-services-6-item-desc">无论数据量如何，BetSPSSModeler会提供封装和自定义机器学习，以满足您的使用体验，将机器数据转化为答案。</p>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4 col-sm-6">';
		str+='					<div class="c-content-services-6-item wow fadeInUp" data-wow-delay="0.2s">';
		str+='						<div class="c-content-services-6-item-icon c-content-business-line-icon c-theme c-business-icon-12"></div>';
		str+='						<h4 class="c-content-services-6-item-title">超高性价比</h4>';
		str+='						<p class="c-content-services-6-item-desc">我们的产品在保证高命中率的同时，极大的压缩了运营维护成本，使得您花费更少的金钱，获得更高的回报。</p>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4 col-sm-6">';
		str+='					<div class="c-content-services-6-item wow fadeInUp" data-wow-delay="0.4s">';
		str+='						<div class="c-content-services-6-item-icon c-content-business-line-icon c-theme c-business-icon-29"></div>';
		str+='						<h4 class="c-content-services-6-item-title">互联网思维</h4>';
		str+='						<p class="c-content-services-6-item-desc">触点式思维模型管理，确保预测模型的及时准确性，实时了解各个变量的影响，使得预测结果更可靠。</p>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4 col-sm-6">';
		str+='					<div class="c-content-services-6-item wow fadeInUp" data-wow-delay="0.6s">';
		str+='						<div class="c-content-services-6-item-icon c-content-business-line-icon c-theme c-business-icon-18"></div>';
		str+='						<h4 class="c-content-services-6-item-title">数据仓库与云分析</h4>';
		str+='						<p class="c-content-services-6-item-desc">BetSPSSModeler拥有自动化的PB量级数据仓库，基于云端的智能分析成本降低到了传统解决方案的十分之一。</p>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4 col-sm-6">';
		str+='					<div class="c-content-services-6-item wow fadeInUp" data-wow-delay="0.8s">';
		str+='						<div class="c-content-services-6-item-icon c-content-business-line-icon c-theme c-business-icon-24"></div>';
		str+='						<h4 class="c-content-services-6-item-title">购买方式</h4>';
		str+='						<p class="c-content-services-6-item-desc">我们采用充值卡续费模式，支持多种支付方式<br>支付平台：WebChat微信、Alipay支付宝及其他渠道</p>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4 col-sm-6">';
		str+='					<div class="c-content-services-6-item wow fadeInUp" data-wow-delay="1s">';
		str+='						<div class="c-content-services-6-item-icon c-content-business-line-icon c-theme c-business-icon-27"></div>';
		str+='						<h4 class="c-content-services-6-item-title">更全面</h4>';
		str+='						<p class="c-content-services-6-item-desc">BetSPSSModeler涵盖了当天所有足球赛事的大小球、亚盘、欧赔初盘预测分析，使您更深入的洞察预测结果。</p>';
		str+='					</div>';
		str+='				</div>				';
		str+='			</div>';
		str+='		</div>';
		str+='	</div>';
		$("#rjys").append(str);
		str='';
		str+='<div class="container">';
		str+='		<div class="c-content-title-1 c-opt-1 wow fadeInDown">';
		str+='			<h3 class="c-font-34 c-font-center c-font-bold c-margin-b-30 c-font-white">';
		str+='				产品特性';
		str+='			</h3>';
		str+='			<p class="c-font-center c-font-grey">让客户满意是我们的首要目标，也是我们的工作理念。</p>';
		str+='			<div class="c-line-center c-theme-bg"></div>';
		str+='		</div>';
		str+='		<div class="c-content-tab-6 c-opt-1" role="tabpanel">';
		str+='			<div class="row">';
		str+='				<div class="col-md-3">';
		str+='					<ul class="nav" role="tablist">';
		str+='						<li role="presentation" class="active wow fadeInLeft" data-wow-delay="0s">';
		str+='							<a href="#tab-1" role="tab" data-toggle="tab">强大的功能</a>';
		str+='						</li>';
		str+='						<li role="presentation" class="wow fadeInLeft" data-wow-delay="0.2s">';
		str+='							<a href="#tab-2" role="tab" data-toggle="tab">准确率保证</a>';
		str+='						</li>';
		str+='						<li role="presentation" class="wow fadeInLeft" data-wow-delay="0.6s">';
		str+='							<a href="#tab-3" role="tab" data-toggle="tab">产品价格</a>';
		str+='						</li>';
		str+='						<li role="presentation" class="wow fadeInLeft" data-wow-delay="0.8s">';
		str+='							<a href="#tab-4" role="tab" data-toggle="tab">24小时自助开通流程</a>';
		str+='						</li>';
		str+='					</ul>';
		str+='				</div>';
		str+='				<div class="col-md-9">';
		str+='					<div class="tab-content c-bg-white wow fadeInRight">';
		str+='						<div role="tabpanel" class="tab-pane fade in active" id="tab-1">';
		str+='							<ul class="c-tab-items">';
		str+='								<li class="row">';
		str+='									<div class="col-sm-4 col-xs-12">';
		str+='										<img class="img-responsive" width="395" height="260"';
		str+='											src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zs.jpg"  alt="功能图片"/>';
		str+='									</div>';
		str+='									<div class="col-sm-8 col-xs-12">';
		str+='										<h4>强大的功能</h4>';
		str+='										<p>我们内置了多种功能模块，高维度分析预测，便于您做出更好的决策。<br>';
		str+='										我们的产品极易上手，对于完全没有接触的用户，只需根据模块说明，就可以顺畅完成赛事的实时预测。<br>';
		str+=' 										详情参考：<a href="contact.html" target="_blank" >BetSPSSModeler软件介绍</a>';
		str+=' 										</p>';
		str+='									</div>';
		str+='								</li>';
		str+='							</ul>';
		str+='						</div>';
		str+='						<div role="tabpanel" class="tab-pane fade" id="tab-2">';
		str+='							<ul class="c-tab-items">';
		str+='								<li class="row">';
		str+='									<div class="col-sm-4 col-xs-12">';
		str+='										<img class="img-responsive" width="350" height="230"';
		str+='											src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zql.jpg"  alt="准确率保证"/>';
		str+='									</div>';
		str+='									<div class="col-sm-8 col-xs-12">';
		str+='										<h4>准确率保证</h4>';
		str+='										<p>我们的软件经过常年测试，保持着70%以上的命中率。<br>';
		str+='										BetSPSSModeler结合SPSS Modeler数据挖掘模型，以其强大的挖掘功能，通过分析结构化数据和非结构化数据，更快速地发现洞察并进行未来赛事预测。<br>';
		str+='										详情参考：<a href="event/events.html" target="_blank"  style="color: #6aaaf4;font-weight: 400;">BetSPSSModeler历史战绩</a>';
		str+='										</p>';
		str+='									</div>';
		str+='								</li>';
		str+='							</ul>';
		str+='						</div>';
		str+='						<div role="tabpanel" class="tab-pane fade" id="tab-3">';
		str+='							<ul class="c-tab-items">';
		str+='								<li class="row">';
		str+='									<div class="col-sm-4 col-xs-12">';
		str+='										<img class="img-responsive" width="350" height="230"';
		str+='											src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/xt.jpg"  alt="产品价格"/>';
		str+='									</div>';
		str+='									<div class="col-sm-8 col-xs-12">';
		str+='										<h4>产品价格</h4>';
		str+='										<p>';
		str+='										我们采用充值卡续费模式，提供了三种购买方式：<br>';
		str+='										按月收费:1500人民币<br>';
		str+='										按季收费:2300人民币<br>';
		str+='										按年收费:4000人民币';
		str+='										</p>';
		str+='									</div>';
		str+='								</li>';
		str+='							</ul>';
		str+='						</div>';
		str+='						<div role="tabpanel" class="tab-pane fade" id="tab-4">';
		str+='							<ul class="c-tab-items">';
		str+='								<li class="row">';
		str+='									<div class="col-sm-4 col-xs-12">';
		str+='										<img class="img-responsive" width="350" height="230"';
		str+='											src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zf.jpg"  alt="安装说明"/>';
		str+='									</div>';
		str+='									<div class="col-sm-8 col-xs-12">';
		str+='										<h4>24小时自助开通流程</h4>';
		str+='										<p>';
		str+='										1、下载系统软件。<br>';
		str+='										2、完成帐号注册操作。<br>';
		str+='										3、进入自助充值页面，点击在线商店，选择指定充值卡类型购买。<br>';
		str+='										4、进入自助充值页面，填写帐号、充值卡号密码，完成充值。<br>';
		str+='										5、软件充值即时生效，使用注册账号用户名密码即可登录使用。<br>';
		str+='										详情参考：<a href="./product/help.html" target="_blank" >BetSPSSModeler使用帮助文档</a>';
		str+='										</p>';
		str+='									</div>';
		str+='								</li>';
		str+='							</ul>';
		str+='						</div>';
		str+='					</div>';
		str+='				</div>';
		str+='			</div>';
		str+='		</div>';
		str+='	</div>';
		$("#cptx").append(str);
		str='';
		str+='﻿	<div class="container">';
		str+='		<div class="c-content-title-1 c-opt-1 wow fadeInDown">';
		str+='			<h3 class="c-center c-font-bold">关于我们</h3>';
		str+='			<p class="c-font-center">成长之路需要无畏和坚持，不断提高预测的准确性是我们成长的动力</p>';
		str+='			<div class="c-line-center c-theme-bg"></div>';
		str+='		</div>';
		str+='		<div class="c-content-events-1">';
		str+='			<div class="row">';
		str+='				<div class="col-md-4">';
		str+='					<div class="c-content-events-1-item wow fadeInLeft" data-wow-delay="0.2s">';
		str+='						<div class="c-content-events-1-img-container">';
		str+='							<img class="c-content-events-1-img" src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/10.jpg" alt="产品问世" style="width:350px;height:224px;"/>';
		str+='						</div>';
		str+='						<div class="c-content-events-1-content-container">';
		str+='							<div class="c-content-events-1-cat">Bet SPSS Modeler</div>';
		str+='							<h3 class="c-content-events-1-title">我们还在成长!</h3>';
		str+='							<p class="c-content-events-1-desc">2017年由BetSPSSModeler分析团队自主研发的一款足球大数据分析平台应运而生，同时与大数据预测分析';
		str+='							面临的挑战一起出现。</p>';
		str+='						</div>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4">';
		str+='					<div class="c-content-events-1-item wow fadeInLeft">';
		str+='						<div class="c-content-events-1-img-container">';
		str+='							<img class="c-content-events-1-img" alt="全新版本"  src="https://cdn.jsdelivr.net/gh/wdlairpgv62/img/img/zq/6.jpg"/>';
		str+='						</div>';
		str+='						<div class="c-content-events-1-content-container">';
		str+='							<div class="c-content-events-1-cat">Bet SPSS Modeler v2.0</div>';
		str+='							<h3 class="c-content-events-1-title">全新版本已经问世!</h3>';
		str+='							<p class="c-content-events-1-desc">2019年初v2.0版本问世，提供了更强大的分析预测功能，真正实现了超大数据量的自助式分析。</p>';
		str+='						</div>';
		str+='					</div>';
		str+='				</div>';
		str+='				<div class="col-md-4">';
		str+='					<div class="c-content-events-1-item c-events-1-featured wow fadeIn" data-wow-delay="0.5s" data-wow-duration="1s">';
		str+='						<div class="c-content-events-1-content-container">';
		str+='							<div class="c-content-events-1-cat">V5.0.1正式发布</div>';
		str+='							<p class="c-content-events-1-desc" style="margin-top:5px;">在全新版本中我们为您带来了更好的内容：</p>';
		str+='							<ul class="c-content-events-1-list">';
		str+='								<li class="c-content-events-1-list-item">';
		str+='									<span>拥有强大数据挖掘算法的深度与广度的软件环境</span>';
		str+='								</li>';
		str+='								<li class="c-content-events-1-list-item">';
		str+='									<span>提供固化分析预测</span>';
		str+='								</li>';
		str+='								<li class="c-content-events-1-list-item">';
		str+='									<span>解锁更多赛事</span>';
		str+='								</li>';
		str+='								<li class="c-content-events-1-list-item">';
		str+='									<span>核心运算引擎重塑，进一步提高预测准确性</span>';
		str+='								</li>';
		str+='							</ul>';
		str+='						</div>';
		str+='					</div>';
		str+='				</div>';
		str+='			</div>';
		str+='		</div>';
		str+='	</div>';
		$("#gywm").append(str);
		
		
		
		

	};


	return {
		init: function () {
			initBT();
		}
	};
}();

jQuery(document).ready(function() {
	initIndex.init();
});